version: "3.9"

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-bichobet}
      POSTGRES_USER: ${POSTGRES_USER:-bichobet}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-bichobet}
      TZ: ${TZ:-UTC}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-bichobet} -d ${POSTGRES_DB:-bichobet}"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata: